language: elixir

stages:
  - test
  - quality

elixir: 1.7
otp_release: 21.1

jobs:
  include:
    - stage: test
      script: mix test

    - stage: quality
      script: mix format --check-formatted

    - stage: quality
      script: mix credo --strict
